name: Java CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Compile Java
        run: javac HelloWorld.java

      - name: Run Java
        run: java HelloWorld
